### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by Johan-4P** [Johan-4P/Mysterious-Things#1]
As a first time visitor. I whant to easely navigation, including  a responsiv layout for my device so i can find information without frustration

**Acceptance Criteria:**

- [ ]  Engaging descriptions of the diffrent content's page
- [ ] The home page layout prominently features the images and descriptions in an uncluttered manner 

**Tasks:**

- [ ]  Well written text that is easy to understand even for beginners 
- [ ] Design and implement a homepage layout that prominentöy features the images and discriptions.
