### ISSUE TITLE
well written information

### ISSUE THREAD

**Issue by Johan-4P** [Johan-4P/Mysterious-Things#2]
As a beginner . I whant to see lot information about what interests me. 

**Acceptance Criteria:**

- [ ]  Engaging descriptions of the diffrent content's page
- [ ] The home page layout prominently features the images and descriptions in an uncluttered manner 

**Tasks:**

- [ ]  Well written text that is easy to understand even for beginners 
- [ ] Design and implement a homepage layout that prominentöy features the images and discriptions.
