### ISSUE TITLE
Selling site ?

### ISSUE THREAD

**Issue by Johan-4P** [Johan-4P/Mysterious-Things#3]
If i get so interested about that im looking at can i then buy it?
if not, where can i find it?

**Acceptence Criteria:**

- [ ]  Create a page for selling products
- [ ] External links there you can buy the items you need 

**Tasks**

- [ ]  Create a well-functioning page for selling products
- [ ] Or links to a site that are selling this product
