### ISSUE TITLE
Oracle Deck Page

### ISSUE THREAD

**Issue by Johan-4P** [Johan-4P/Mysterious-Things#4]
As a visitor, I want to view different Oracle cards, so I can appreciate their messages.

**Acceptance Criteria:**

- [x] The page displays a carousel of Oracle cards.
- [x] The page has a consistent, elegant design.

**Tasks:**

- [x] Create a carousel for Oracle cards using bootstrap.
- [x] Use consistent design elements with other pages.
